"""Default constants for BreakTheVibe."""

# Crawler defaults
DEFAULT_MAX_DEPTH = 5
DEFAULT_VIEWPORT_WIDTH = 1280
DEFAULT_VIEWPORT_HEIGHT = 800
DEFAULT_PAGE_LOAD_TIMEOUT_MS = 30_000
DEFAULT_AFTER_CLICK_WAIT_MS = 1_000
DEFAULT_SCROLL_WAIT_MS = 500
MAX_SCROLL_ATTEMPTS = 10

# Runner defaults
DEFAULT_PARALLEL_WORKERS = 4
DEFAULT_MAX_RETRIES = 1
DEFAULT_RETRY_DELAY_MS = 2_000

# LLM defaults
DEFAULT_LLM_PROVIDER = "anthropic"
DEFAULT_LLM_MODEL = "claude-sonnet-4-20250514"
DEFAULT_LLM_MAX_TOKENS = 4096

# Storage
DEFAULT_ARTIFACTS_DIR = "~/.breakthevibe/artifacts"
