"""add_test_case_cache_fields

Revision ID: 762fda7c165f
Revises: fa6cd78ab556
Create Date: 2026-03-23 23:51:02.670798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '762fda7c165f'
down_revision: Union[str, Sequence[str], None] = 'fa6cd78ab556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_runs', sa.Column('sitemap_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_crawl_runs_sitemap_hash'), 'crawl_runs', ['sitemap_hash'], unique=False)
    op.add_column('test_cases', sa.Column('crawl_run_id', sa.Integer(), nullable=True))
    op.add_column('test_cases', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('test_cases', sa.Column('sitemap_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('test_cases', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_test_cases_crawl_run_id'), 'test_cases', ['crawl_run_id'], unique=False)
    op.create_index('ix_test_cases_project_hash', 'test_cases', ['project_id', 'sitemap_hash'], unique=False)
    op.create_foreign_key(None, 'test_cases', 'crawl_runs', ['crawl_run_id'], ['id'])
    op.drop_column('test_cases', 'selectors_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('selectors_json', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'test_cases', type_='foreignkey')
    op.drop_index('ix_test_cases_project_hash', table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_crawl_run_id'), table_name='test_cases')
    op.drop_column('test_cases', 'updated_at')
    op.drop_column('test_cases', 'sitemap_hash')
    op.drop_column('test_cases', 'description')
    op.drop_column('test_cases', 'crawl_run_id')
    op.drop_index(op.f('ix_crawl_runs_sitemap_hash'), table_name='crawl_runs')
    op.drop_column('crawl_runs', 'sitemap_hash')
    # ### end Alembic commands ###
