"""add_sessions_and_indexes

Revision ID: fa6cd78ab556
Revises: g7h8i9j0k1l2
Create Date: 2026-03-20 21:10:30.345981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa6cd78ab556'
down_revision: Union[str, Sequence[str], None] = 'g7h8i9j0k1l2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_pipeline_jobs_org_id'), table_name='pipeline_jobs')
    op.drop_table('pipeline_jobs')
    op.create_index('ix_crawl_runs_org_project_created', 'crawl_runs', ['org_id', 'project_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_llm_settings_key'), table_name='llm_settings')
    op.create_index(op.f('ix_llm_settings_key'), 'llm_settings', ['key'], unique=False)
    op.create_unique_constraint(None, 'llm_settings', ['org_id', 'key'])
    op.create_index('ix_projects_org_created', 'projects', ['org_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('subscriptions_org_id_key'), 'subscriptions', type_='unique')
    op.drop_index(op.f('ix_subscriptions_org_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_org_id'), 'subscriptions', ['org_id'], unique=True)
    op.create_index('ix_test_results_run_status', 'test_results', ['test_run_id', 'status'], unique=False)
    op.alter_column('test_runs', 'completed_stages_json',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('test_runs', 'error_message',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('test_runs', 'suites_json',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('test_runs', 'heal_warnings_json',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_index('ix_test_runs_org_project_created', 'test_runs', ['org_id', 'project_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('webauthn_credentials_credential_id_key'), 'webauthn_credentials', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('webauthn_credentials_credential_id_key'), 'webauthn_credentials', ['credential_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_test_runs_org_project_created', table_name='test_runs')
    op.alter_column('test_runs', 'heal_warnings_json',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('test_runs', 'suites_json',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('test_runs', 'error_message',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('test_runs', 'completed_stages_json',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index('ix_test_results_run_status', table_name='test_results')
    op.drop_index(op.f('ix_subscriptions_org_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_org_id'), 'subscriptions', ['org_id'], unique=False)
    op.create_unique_constraint(op.f('subscriptions_org_id_key'), 'subscriptions', ['org_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_projects_org_created', table_name='projects')
    op.drop_constraint(None, 'llm_settings', type_='unique')
    op.drop_index(op.f('ix_llm_settings_key'), table_name='llm_settings')
    op.create_index(op.f('ix_llm_settings_key'), 'llm_settings', ['key'], unique=True)
    op.drop_index('ix_crawl_runs_org_project_created', table_name='crawl_runs')
    op.create_table('pipeline_jobs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.VARCHAR(), server_default=sa.text("'full'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('rules_yaml', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pipeline_jobs_pkey'))
    )
    op.create_index(op.f('ix_pipeline_jobs_org_id'), 'pipeline_jobs', ['org_id'], unique=False)
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
